parallel-jobs = 1

# Morphe
[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"

[Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

# Piko
[X]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
patches-source = "crimera/piko"
cli-source = "inotia00/revanced-cli"
brand = "Piko"
included-patches = "'Dynamic color'"